namespace: (from-context)

deployments:
  - name: required
    spec:
      template:
        spec:
          containers:
          - image: required
            port: required

ingresses:
  - name: required
    path: required
    rules:
    - http:
        paths:
        - backend:
            service:
              port: required

helms:
  - (path)
    values:
      value1:
      value2: